### ISSUE TITLE
Change Name Titles

### ISSUE THREAD

**Issue by SCarns** [itemir/signalk-saillogger#18]
I'd like to request you display boat name instead of my first name on the display pages. SignalK and Saillogger are always with the boat, even when I'm not on it, so it makes sense to show the ship's log, instead of my personal log.

**Comment by itemir** [comment]
This is intentional. This is really an individual log. You can have multiple boats (which we did) and there can be multiple people linked to a single boat (we have that too) and the same people can be linked to multiple other boats at other times (think chartering). 

Not all of these are exposed on the UI but the data model and the working semantics are structured around it.
